server:
  port: 8084

spring:
  application:
    name: payment-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/team42?currentSchema=payment_schema}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:root}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:Quanfey}}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        default_schema: payment_schema

app:
  mock-gateway-url: ${MOCK_GATEWAY_URL:http://localhost:9000}
  callback-url: ${CALLBACK_URL:http://localhost:8084/api/v1/payments/webhook}
  gateway-secret: ${GATEWAY_SECRET:z2p-2026-secret}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
